### ISSUE TITLE
[Vertex AI] PluginInvokeError was randomly raise

### ISSUE THREAD

**Issue by AlexChim1231** [langgenius/dify-official-plugins#1134]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [Dify issues](https://github.com/langgenius/dify/issues) & [Dify Official Plugins](https://github.com/langgenius/dify-official-plugins/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.2

### Plugin version

0.0.16, 0.0.19, 0.0.20

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

While using Gemini though Vertex AI, the PluginInvokeError will be randomly throw, the workflow is only start -> gemini -> end.

This error would not raise for every request. We try different version of Vertex AI plugin and location and still error.

Unfortunately I cannot trace the log from docker because the response is 200, there is no any log for this error, this also created an [issue](https://github.com/langgenius/dify/issues/21262) in dify repo.

For the temporary solution:
retry 5 times for each llm node using gemini

related error:
Failed to transform tool message: [vertex_ai] Error: PluginInvokeError: {"args":{},"error_type":"IndexError","message":"list index out of range"}
Failed to transform tool message: [vertex_ai] Error: PluginInvokeError: {"args":{},"error_type":"AttributeError","message":"'list' object has no attribute 'get'"}
Failed to transform tool message: [vertex_ai] Error: PluginDaemonInternalServerError: killed by timeout

Screen Cap:
1. Dify log
![Image](https://github.com/user-attachments/assets/5d43886c-f178-498a-b218-f73538821c7c)

### ✔️ Error log

No any error log, only success log in [issue](https://github.com/langgenius/dify/issues/21262)

**Comment by unmo** [comment]
same problem

**Comment by AlexChim1231** [comment]
After I upgrade Dify to v1.5.0+, I see this in debug panel. Is that the output from Vertex AI be changed?

<img width="1168" height="531" alt="Image" src="https://github.com/user-attachments/assets/63af8878-8b46-4e61-8704-21bed29f1191" />

**Comment by AlexChim1231** [comment]
@unmo 
Any update for this?

After i debug for this error, it is actually a not success response from vertex ai. in my case i set the unsupport location, and it return a 404 response with list.

However, Google api sdk only consider the response is a dict/object instead a list in python, so we see this error in Dify web ui.

<img width="1234" height="734" alt="Image" src="https://github.com/user-attachments/assets/67afe4ef-f7c4-408e-99dd-2ee4fdbe8532" />

**Comment by AlexChim1231** [comment]
[Issue](https://github.com/googleapis/google-cloud-python/issues/15021) to google api core

**Comment by unmo** [comment]
@AlexChim1231 

For the gemini-2.5-pro model, the available locations are limited. It seems the model is not deployed in asia-northeast1( and asia-southeast1 ), which likely causes the error. Setting the location to us-central1 or another supported region should allow the generation to proceed successfully.

**Comment by AlexChim1231** [comment]
@unmo 

Yes, after i change to us-central1 and gemini 2.5 pro (not preview, it also disabled) then work fine.

Thank you
