### ISSUE TITLE
LLM nodes using Gemini 2.5 series models throw errors when parsing uploaded files in Chatflow

### ISSUE THREAD

**Issue by bossyang** [langgenius/dify-official-plugins#1609]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [Dify issues](https://github.com/langgenius/dify/issues) & [Dify Official Plugins](https://github.com/langgenius/dify-official-plugins/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.2

### Plugin version

0.0.23

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a Chatflow app
2. Create a file variable in Start node
3. Select the Gemini 2.5 model, check the Visual option, and associate the variable from the previous step.
4. It works with Claude Sonnet 4. All models are provided by the Vertex AI plugin.

### Gemini 2.5
<img width="2074" height="871" alt="Image" src="https://github.com/user-attachments/assets/03208f96-8d84-4db3-89b8-c37b43824ccf" />

### Claude Sonnet 4 
<img width="2019" height="1253" alt="Image" src="https://github.com/user-attachments/assets/3f7dab6f-7615-4102-b2f3-fd43d21ec0cc" />

### ✔️ Error log

```
Run failed: [vertex_ai] Error: req_id: 711e14f23b PluginInvokeError: {"args":{},"error_type":"AttributeError","message":"'list' object has no attribute 'get'"}
```

**Comment by skyking363** [comment]
+1

**Comment by bossyang** [comment]
It works in Dify 1.8.1, vertex_ai 0.0.24. Thank you @Dosu.
